#!/usr/bin/env node
/**
 * Build script: generates src/pages.js from pages/*.html
 * Embeds each HTML page as a string in an exported object.
 * The trap page is also embedded in the worker separately.
 *
 * Run: node scripts/build.js
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const pagesDir = path.resolve(root, "pages");
const outFile = path.resolve(root, "src", "pages.js");

const files = fs.readdirSync(pagesDir).filter((f) => f.endsWith(".html"));
const entries = [];

for (const file of files) {
  const key = file.replace(/\.html$/, "");
  const content = fs.readFileSync(path.join(pagesDir, file), "utf-8");
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${");
  entries.push({ key, content: escaped });
}

const output = `// Auto-generated by scripts/build.js
// Do not edit directly — edit pages/*.html instead

export const PAGES = {
${entries.map((e) => `  "${e.key}": \`${e.content}\`,`).join("\n")}
};
`;

fs.writeFileSync(outFile, output);
console.log(`✓ Generated ${outFile} with ${entries.length} pages (${(Buffer.byteLength(output, "utf-8") / 1024 / 1024).toFixed(1)} MB)`);
