#!/usr/bin/env node
/**
 * Build script: generates src/pages.js from pages/*.html
 * This embeds each HTML page as an exported constant in a JS module.
 */
const fs = require("fs");
const path = require("path");

const pagesDir = path.resolve(__dirname, "..", "pages");
const outFile = path.resolve(__dirname, "..", "src", "pages.js");

const files = fs.readdirSync(pagesDir).filter((f) => f.endsWith(".html"));
const entries = [];

// Trap page (special case)
for (const file of files) {
  const key = file.replace(/\.html$/, "");
  const content = fs.readFileSync(path.join(pagesDir, file), "utf-8");
  // Escape backticks and ${} for template literals
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
  entries.push({ key, content: escaped });
}

let output = `// Auto-generated by scripts/build.js — do not edit directly
// Generated from pages/*.html on ${new Date().toISOString()}

export const PAGES = {\n`;

for (const { key, content } of entries) {
  output += `  "${key}": \`${content}\`,\n`;
}

output += `};\n`;

fs.writeFileSync(outFile, output);
console.log(`Generated ${outFile} with ${entries.length} pages`);
